#!/bin/bash

## start/stop-script
## by Philipp Tendyra and Samuel Schueppen
# copy to /etc/init.d/swe-server

##DAEMON: User-Name for screen
##Params: start-parameters

DAEMON=$1
CMD="su - $DAEMON -c '/home/$DAEMON/startServer'"

start() {

if [ `whoami` != "swedaemon" ]; then
	echo "Wrong User : "'whoami'
	exit 1
fi

screen -dmS $DAEMON $CMD
}

stop() {


if [ `whoami` != "swedaemon" ]; then
	echo "Wrong User : "'whoami'
	exit 1
fi

#screen -S $DAEMON -X stuff $'0\n'

screen kill $DAEMON
}

restart() {
	stop
	start

}

case "$2" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	restart
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
