#!/bin/bash

apt-get install sudo lshw lscpu proftpd-basic screen ssh openjdk-1.6-jdk php5 apache2
if [ $? = 0 ]
then 
	echo everything installed
else
	echo bad things happen everywhere
	echo try once again
	exit 1
fi

