#!/bin/bash
## This Script is for the Host
## by Philipp Tendyra

proof=0
apt-get install sudo proftpd-basic screen ssh openjdk-1.6-jdk php5 apache2
proof="$proof $?"

echo 'start configuration'
daemon='swedaemon'
ftpu='sweftp'
ftpg='ftpuser'

# system config
adduser $daemon -home /home/$daemon -shell /bin/bash
proof="$proof $?"

cp ftpget 	/home/$daemon/ftpget
cp startServer	/home/$daemon/startServer
cp software	/home/$daemon/software
cp status	/home/$daemon/status
cp start	/home/$daemon/start
cp stop		/home/$daemon/stop
cp restart	/home/$daemon/restart
cp installService /home/$daemon/installService
cp swe-server /etc/init.d/swe-server
cp Server.jar /home/$daemon/Server.jar


chmod +x /home/$daemon/ftpget
chmod +x /home/$daemon/startServer
chmod +x /home/$daemon/software
chmod +x /home/$daemon/installService
chmod +x /home/$daemon/status
chmod +x /home/$daemon/start
chmod +x /home/$daemon/stop
chmod +x /home/$daemon/restart
chmod +x /etc/init.d/swe-server
chmod +x /home/$daemon/Server.jar
chown $daemon:$daemon /home/$daemon/Server.jar

update-rc.d /etc/init.d/swe-server defaults
proof="$proof $?"

mkdir /home/$daemon/repository
proof="$proof $?"
chown $daemon:$daemon /home/$daemon/repository





# apache config
# default should do for the moment

# ftp config
ftpconfig='/etc/proftpd/proftpd.conf'

echo	>>$ftpconfig 
echo	'# script-generated code'>>$ftpconfig 
echo '<Global>'>>$ftpconfig 
echo 'RequireValidShell off'>>$ftpconfig 
echo '</Global>'>>$ftpconfig 
echo	>>$ftpconfig 
echo 'DefaultRoot ~ ftpuser'>>$ftpconfig 
echo
echo '<Limit LOGIN>'>>$ftpconfig 
echo 'DenyGroup !ftpuser'>>$ftpconfig 
echo '</Limit>'>>$ftpconfig
echo '# end of script-generated code'>>$ftpconfig

/etc/init.d/proftpd restart
proof="$proof $?"

addgroup $ftpg
p1=$?
proof="$proof $p1"

if [ $p1 = 0]
	adduser $daemon $ftpg
	proof="$proof $?"
	adduser $ftpu -shell /bin/false -home /home/$daemon/repository
	proof="$proof $?"
	adduser $ftpu $ftpg
	proof="$proof $?"
else
	exit 1
fi


for i in $proof
do
	if [ $i != 0 ]
	echo 'an error occured'	
	echo $proof
	exit 1
done






